Add acceptance tests for multibuy screens
DEFRA/rod-licensing-tests pull request #231
Opened 2021-11-10 14:49 UTC by nabeelamir-defra

https://eaflood.atlassian.net/browse/IWTF-2267

Add acceptance tests for multibuy screens - licence for, name, dob and concessions

2021-11-11 12:49 UTC, jaucourt requested changes
Check the 'given' step, as it combines several and can make the tests a bit less verbose

2021-11-11 13:18 UTC, nabeelamir-defra commented on packages/frontend-acceptance-tests/src/features/2 - 12 Month Licences/5_benefit_licence-12-months_immediate_start.feature
>      Given I select a "salmon" fishing licence
Thanks for your comment Phil. I agree with what you have said, but it’s a lot more difficult to do than you think. So the above code I added was actually a section called background, which means it's called each time before a test is run. However, the name screen is now the second screen which is variable, so I had to move the code out.

What you're probably suggesting combining:
*   I am 7 days over my 17th birthday
*   I enter “Benefit” as the ni concession and I enter “NP382939C” as the concesssion id
    And  I select Now as a start time
Given I select a "salmon" fishing licence

To simply ’I select a ‘x’ licence’ doesn’t give an indication as to what is actually going on and will cause more confusion. You’d have to look at the code to see what is being selected etc. You could combine it into one line, but in that case you might as well have it on separate lines.

The specific file you have commented isn't very well laid out. I like what they’ve done to this file https://github.com/DEFRA/rod-licensing-tests/blob/839dae5e6c2e4752672537546f7b30e610b77ea7/packages/frontend-acceptance-tests/src/features/1%20-%201%20and%208%20Day%20Licences/1_adult_1_or_8_day_licence_immediate_start.feature And I think we should be adopting that approach in this file. But we should create a separate ticket for the work.

2021-11-12 08:36 UTC, naimullakhandefra approved these changes

2021-11-12 08:52 UTC, jaucourt approved these changes

2021-11-12 10:03 UTC, merged